### ISSUE TITLE
Updates of TransitGatewayAttachment shouldn't trigger resource replacement

### ISSUE THREAD

**Issue by kallu** [aws-cloudformation/aws-cloudformation-resource-providers-transitgateway#124]
Current implementation of TransitGatewayAttachment triggers resource replacement for all(?) changes. Even simple things such as applying new tags to Cloudformation stack will cause TGW attachment to be replaced. Problem with replacement is, it will always fail because how Cloudformation replacement logic works. Cloudformation will first create the new resource and then remove the old one. This makes sense to be able to roll-back if new resource can not be created, but will make replacement of TGW attachment impossible as there can not be multiple attachment from single TGW to VPC. Most (all?) of attachment attributes can be reconfigured via API (or cli/console) without recreating the attachment, so it should be possible for Cloudformation provider too?

<img width="1252" alt="update-error" src="https://user-images.githubusercontent.com/154476/163539536-4da274de-a5ac-48f4-bc4c-feebaa456030.png">

**Comment by harshitjain99** [comment]
The changeset preview shows the resource replacment as false when we are updating the tags for TransitGatewayAttachment  via CFN. This is a incorrect information as the resource tag update require replacement as per the docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayattachment.html.

Apart from this false info on changesetset preview I would like add my vote that CFN should not replace the TransitGatewayAttachment on the tag updates as this leads to error because CFN will create the new resource which will fail as you can only have one attachment between the same VPC and transit gateway pair.

**Comment by kallu** [comment]
It looks like the fix for this has been rolling out. I had it working already last weekend at eu-central-1 and as just tested in us-west-1 it was working there as well. Here is how my Cloudformation changeset looks when applying a new tag to stack.
![Screenshot 2022-05-24 at 9 12 00](https://user-images.githubusercontent.com/154476/169961590-83d2f81f-e199-4f48-8784-8fc4b756cab6.png)

**Comment by harshitjain99** [comment]
Thanks a lot for your response.
I find out that the issue has been resolved on a new resource AWS::EC2::TransitGatewayVpcAttachment
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayvpcattachment.html
But the issue is still there on old resource AWS::EC2::TransitGatewayAttachment and I reckon the best way is to migrate to AWS::EC2::TransitGatewayVpcAttachment as this allows updating the tags without replacement.

**Comment by kallu** [comment]
Didn't notice that difference. There seems to be very little documentation what would be the use-case of ```AWS::EC2::TransitGatewayAttachment``` that you couldn't do with ```AWS::EC2::TransitGatewayVpcAttachment``` so I assume first one is left there for backwards compatibility but shouldn't be used. It would be nice to mention there is improved version available on ```AWS::EC2::TransitGatewayAttachment``` docs though.
